/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kirbinator505_ (https://sketchfab.com/kirbinator505_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/burned-log-1-765e0766db2a4c059934532cf186f5d9
Title: Burned Log 1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export default function BurnedLog(props) {
  const { nodes, materials } = useGLTF('/models/burned_log.glb')
  return (
    <RigidBody>
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="59ecbd49511a40ce8b17a143257fe15dobjcleanermaterialmergergles">
            <mesh
              name="Object_2"
              castShadow
              receiveShadow
              geometry={nodes.Object_2.geometry}
              material={materials.lambert4SG}
            />
          </group>
        </group>
      </group>
    </group>
    </RigidBody>
  )
}

useGLTF.preload('/models/burned_log.glb')
