/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: patrakeevasveta (https://sketchfab.com/patrakeevasveta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dancing-cactus-day-15-f4fd1591bb6944d8a0ed93b45ea8fa23
Title: Dancing cactus - Day 15
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";
import { useFrame } from "@react-three/fiber";
export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/cactus.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Play animation
    const action = actions["ArmatureAction"];
    if (action) {
      action.reset().fadeIn(0.5).play();
    }

    return () => {
      if (action) action.fadeOut(0.5).stop();
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.128}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="pot_0">
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.cactus}
                />
              </group>
              <group name="Armature_10" position={[-0.051, 1.275, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.cactus}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <group name="body_9" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/cactus.glb");
