/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Centipede(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/centipede.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Play a specific animation (assuming it exists in the GLTF file)
    const action = actions["centipede_rigAction.001"];
    if (action) {
      action.reset().fadeIn(0.5).play();
    }

    return () => {
      if (action) action.fadeOut(0.5).stop(); // Cleanup on component unmount
    };
  }, [actions]);

  return (
    <RigidBody>
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <mesh
            name="CURVE_FOLLOW"
            castShadow
            receiveShadow
            geometry={nodes.CURVE_FOLLOW.geometry}
            material={nodes.CURVE_FOLLOW.material}
          />
          <group name="CTRL_WALK" position={[0.066, 0, 0]} />
          <group name="centipede_rig">
            <skinnedMesh
              name="centipede"
              geometry={nodes.centipede.geometry}
              material={materials.centipede}
              skeleton={nodes.centipede.skeleton}
            />
            <primitive object={nodes.DEF_torso_1} />
            <primitive object={nodes.DEF_leg_1_1_L} />
            <primitive object={nodes.DEF_leg_1_2_L} />
            <primitive object={nodes.DEF_leg_1_3_L} />
            <primitive object={nodes.DEF_leg_1_4_L} />
            <primitive object={nodes.DEF_leg_1_5_L} />
            <primitive object={nodes.DEF_head} />
            <primitive object={nodes.DEF_tendril_1_L} />
            <primitive object={nodes.DEF_tendril_2_L} />
            <primitive object={nodes.DEF_tendril_3_L} />
            <primitive object={nodes.DEF_tendril_4_L} />
            <primitive object={nodes.DEF_tendril_5_L} />
            <primitive object={nodes.DEF_tendril_6_L} />
            <primitive object={nodes.DEF_tendril_7_L} />
            <primitive object={nodes.DEF_hand_1_L} />
            <primitive object={nodes.DEF_hand_2_L} />
            <primitive object={nodes.DEF_hand_3_L} />
            <primitive object={nodes.DEF_hand_4_L} />
            <primitive object={nodes.DEF_tendril_1_R} />
            <primitive object={nodes.DEF_tendril_2_R} />
            <primitive object={nodes.DEF_tendril_3_R} />
            <primitive object={nodes.DEF_tendril_4_R} />
            <primitive object={nodes.DEF_tendril_5_R} />
            <primitive object={nodes.DEF_tendril_6_R} />
            <primitive object={nodes.DEF_tendril_7_R} />
            <primitive object={nodes.DEF_hand_1_R} />
            <primitive object={nodes.DEF_hand_2_R} />
            <primitive object={nodes.DEF_hand_3_R} />
            <primitive object={nodes.DEF_hand_4_R} />
            <primitive object={nodes.DEF_nail_1_L} />
            <primitive object={nodes.DEF_nail_2_L} />
            <primitive object={nodes.DEF_leg_1_1_R} />
            <primitive object={nodes.DEF_leg_1_2_R} />
            <primitive object={nodes.DEF_leg_1_3_R} />
            <primitive object={nodes.DEF_leg_1_4_R} />
            <primitive object={nodes.DEF_leg_1_5_R} />
            <primitive object={nodes.DEF_nail_1_R} />
            <primitive object={nodes.DEF_nail_2_R} />
            <primitive object={nodes.DEF_torso_2} />
            <primitive object={nodes.DEF_leg_2_1_L} />
            <primitive object={nodes.DEF_leg_2_2_L} />
            <primitive object={nodes.DEF_leg_2_3_L} />
            <primitive object={nodes.DEF_leg_2_4_L} />
            <primitive object={nodes.DEF_leg_2_5_L} />
            <primitive object={nodes.DEF_leg_2_1_R} />
            <primitive object={nodes.DEF_leg_2_2_R} />
            <primitive object={nodes.DEF_leg_2_3_R} />
            <primitive object={nodes.DEF_leg_2_4_R} />
            <primitive object={nodes.DEF_leg_2_5_R} />
            <primitive object={nodes.DEF_torso_3} />
            <primitive object={nodes.DEF_leg_3_1_L} />
            <primitive object={nodes.DEF_leg_3_2_L} />
            <primitive object={nodes.DEF_leg_3_3_L} />
            <primitive object={nodes.DEF_leg_3_4_L} />
            <primitive object={nodes.DEF_leg_3_5_L} />
            <primitive object={nodes.DEF_leg_3_1_R} />
            <primitive object={nodes.DEF_leg_3_2_R} />
            <primitive object={nodes.DEF_leg_3_3_R} />
            <primitive object={nodes.DEF_leg_3_4_R} />
            <primitive object={nodes.DEF_leg_3_5_R} />
            <primitive object={nodes.DEF_torso_4} />
            <primitive object={nodes.DEF_leg_4_1_L} />
            <primitive object={nodes.DEF_leg_4_2_L} />
            <primitive object={nodes.DEF_leg_4_3_L} />
            <primitive object={nodes.DEF_leg_4_4_L} />
            <primitive object={nodes.DEF_leg_4_5_L} />
            <primitive object={nodes.DEF_leg_4_1_R} />
            <primitive object={nodes.DEF_leg_4_2_R} />
            <primitive object={nodes.DEF_leg_4_3_R} />
            <primitive object={nodes.DEF_leg_4_4_R} />
            <primitive object={nodes.DEF_leg_4_5_R} />
            <primitive object={nodes.DEF_torso_5} />
            <primitive object={nodes.DEF_leg_5_1_L} />
            <primitive object={nodes.DEF_leg_5_2_L} />
            <primitive object={nodes.DEF_leg_5_3_L} />
            <primitive object={nodes.DEF_leg_5_4_L} />
            <primitive object={nodes.DEF_leg_5_5_L} />
            <primitive object={nodes.DEF_leg_5_1_R} />
            <primitive object={nodes.DEF_leg_5_2_R} />
            <primitive object={nodes.DEF_leg_5_3_R} />
            <primitive object={nodes.DEF_leg_5_4_R} />
            <primitive object={nodes.DEF_leg_5_5_R} />
            <primitive object={nodes.DEF_torso_6} />
            <primitive object={nodes.DEF_leg_6_1_L} />
            <primitive object={nodes.DEF_leg_6_2_L} />
            <primitive object={nodes.DEF_leg_6_3_L} />
            <primitive object={nodes.DEF_leg_6_4_L} />
            <primitive object={nodes.DEF_leg_6_5_L} />
            <primitive object={nodes.DEF_leg_6_1_R} />
            <primitive object={nodes.DEF_leg_6_2_R} />
            <primitive object={nodes.DEF_leg_6_3_R} />
            <primitive object={nodes.DEF_leg_6_4_R} />
            <primitive object={nodes.DEF_leg_6_5_R} />
            <primitive object={nodes.DEF_torso_7} />
            <primitive object={nodes.DEF_leg_7_1_L} />
            <primitive object={nodes.DEF_leg_7_2_L} />
            <primitive object={nodes.DEF_leg_7_3_L} />
            <primitive object={nodes.DEF_leg_7_4_L} />
            <primitive object={nodes.DEF_leg_7_5_L} />
            <primitive object={nodes.DEF_leg_7_1_R} />
            <primitive object={nodes.DEF_leg_7_2_R} />
            <primitive object={nodes.DEF_leg_7_3_R} />
            <primitive object={nodes.DEF_leg_7_4_R} />
            <primitive object={nodes.DEF_leg_7_5_R} />
            <primitive object={nodes.DEF_torso_8} />
            <primitive object={nodes.DEF_leg_8_1_L} />
            <primitive object={nodes.DEF_leg_8_2_L} />
            <primitive object={nodes.DEF_leg_8_3_L} />
            <primitive object={nodes.DEF_leg_8_4_L} />
            <primitive object={nodes.DEF_leg_8_5_L} />
            <primitive object={nodes.DEF_leg_8_1_R} />
            <primitive object={nodes.DEF_leg_8_2_R} />
            <primitive object={nodes.DEF_leg_8_3_R} />
            <primitive object={nodes.DEF_leg_8_4_R} />
            <primitive object={nodes.DEF_leg_8_5_R} />
            <primitive object={nodes.DEF_torso_9} />
            <primitive object={nodes.DEF_leg_9_1_L} />
            <primitive object={nodes.DEF_leg_9_2_L} />
            <primitive object={nodes.DEF_leg_9_3_L} />
            <primitive object={nodes.DEF_leg_9_4_L} />
            <primitive object={nodes.DEF_leg_9_5_L} />
            <primitive object={nodes.DEF_leg_9_1_R} />
            <primitive object={nodes.DEF_leg_9_2_R} />
            <primitive object={nodes.DEF_leg_9_3_R} />
            <primitive object={nodes.DEF_leg_9_4_R} />
            <primitive object={nodes.DEF_leg_9_5_R} />
            <primitive object={nodes.DEF_torso_10} />
            <primitive object={nodes.DEF_leg_10_1_L} />
            <primitive object={nodes.DEF_leg_10_2_L} />
            <primitive object={nodes.DEF_leg_10_3_L} />
            <primitive object={nodes.DEF_leg_10_4_L} />
            <primitive object={nodes.DEF_leg_10_5_L} />
            <primitive object={nodes.DEF_leg_10_1_R} />
            <primitive object={nodes.DEF_leg_10_2_R} />
            <primitive object={nodes.DEF_leg_10_3_R} />
            <primitive object={nodes.DEF_leg_10_4_R} />
            <primitive object={nodes.DEF_leg_10_5_R} />
            <primitive object={nodes.DEF_torso_11} />
            <primitive object={nodes.DEF_leg_11_1_L} />
            <primitive object={nodes.DEF_leg_11_2_L} />
            <primitive object={nodes.DEF_leg_11_3_L} />
            <primitive object={nodes.DEF_leg_11_4_L} />
            <primitive object={nodes.DEF_leg_11_5_L} />
            <primitive object={nodes.DEF_leg_11_1_R} />
            <primitive object={nodes.DEF_leg_11_2_R} />
            <primitive object={nodes.DEF_leg_11_3_R} />
            <primitive object={nodes.DEF_leg_11_4_R} />
            <primitive object={nodes.DEF_leg_11_5_R} />
            <primitive object={nodes.DEF_torso_12} />
            <primitive object={nodes.DEF_leg_12_1_L} />
            <primitive object={nodes.DEF_leg_12_2_L} />
            <primitive object={nodes.DEF_leg_12_3_L} />
            <primitive object={nodes.DEF_leg_12_4_L} />
            <primitive object={nodes.DEF_leg_12_5_L} />
            <primitive object={nodes.DEF_leg_12_1_R} />
            <primitive object={nodes.DEF_leg_12_2_R} />
            <primitive object={nodes.DEF_leg_12_3_R} />
            <primitive object={nodes.DEF_leg_12_4_R} />
            <primitive object={nodes.DEF_leg_12_5_R} />
            <primitive object={nodes.DEF_torso_13} />
            <primitive object={nodes.DEF_leg_13_1_L} />
            <primitive object={nodes.DEF_leg_13_2_L} />
            <primitive object={nodes.DEF_leg_13_3_L} />
            <primitive object={nodes.DEF_leg_13_4_L} />
            <primitive object={nodes.DEF_leg_13_5_L} />
            <primitive object={nodes.DEF_leg_13_1_R} />
            <primitive object={nodes.DEF_leg_13_2_R} />
            <primitive object={nodes.DEF_leg_13_3_R} />
            <primitive object={nodes.DEF_leg_13_4_R} />
            <primitive object={nodes.DEF_leg_13_5_R} />
            <primitive object={nodes.DEF_torso_14} />
            <primitive object={nodes.DEF_leg_14_1_L} />
            <primitive object={nodes.DEF_leg_14_2_L} />
            <primitive object={nodes.DEF_leg_14_3_L} />
            <primitive object={nodes.DEF_leg_14_4_L} />
            <primitive object={nodes.DEF_leg_14_5_L} />
            <primitive object={nodes.DEF_leg_14_1_R} />
            <primitive object={nodes.DEF_leg_14_2_R} />
            <primitive object={nodes.DEF_leg_14_3_R} />
            <primitive object={nodes.DEF_leg_14_4_R} />
            <primitive object={nodes.DEF_leg_14_5_R} />
            <primitive object={nodes.DEF_torso_15} />
            <primitive object={nodes.DEF_leg_15_1_L} />
            <primitive object={nodes.DEF_leg_15_2_L} />
            <primitive object={nodes.DEF_leg_15_3_L} />
            <primitive object={nodes.DEF_leg_15_4_L} />
            <primitive object={nodes.DEF_leg_15_5_L} />
            <primitive object={nodes.DEF_leg_15_1_R} />
            <primitive object={nodes.DEF_leg_15_2_R} />
            <primitive object={nodes.DEF_leg_15_3_R} />
            <primitive object={nodes.DEF_leg_15_4_R} />
            <primitive object={nodes.DEF_leg_15_5_R} />
            <primitive object={nodes.DEF_torso_16} />
            <primitive object={nodes.DEF_leg_16_1_L} />
            <primitive object={nodes.DEF_leg_16_2_L} />
            <primitive object={nodes.DEF_leg_16_3_L} />
            <primitive object={nodes.DEF_leg_16_4_L} />
            <primitive object={nodes.DEF_leg_16_5_L} />
            <primitive object={nodes.DEF_leg_16_1_R} />
            <primitive object={nodes.DEF_leg_16_2_R} />
            <primitive object={nodes.DEF_leg_16_3_R} />
            <primitive object={nodes.DEF_leg_16_4_R} />
            <primitive object={nodes.DEF_leg_16_5_R} />
            <primitive object={nodes.DEF_torso_17} />
            <primitive object={nodes.DEF_leg_17_1_L} />
            <primitive object={nodes.DEF_leg_17_2_L} />
            <primitive object={nodes.DEF_leg_17_3_L} />
            <primitive object={nodes.DEF_leg_17_4_L} />
            <primitive object={nodes.DEF_leg_17_5_L} />
            <primitive object={nodes.DEF_leg_17_1_R} />
            <primitive object={nodes.DEF_leg_17_2_R} />
            <primitive object={nodes.DEF_leg_17_3_R} />
            <primitive object={nodes.DEF_leg_17_4_R} />
            <primitive object={nodes.DEF_leg_17_5_R} />
            <primitive object={nodes.DEF_torso_18} />
            <primitive object={nodes.DEF_leg_18_1_L} />
            <primitive object={nodes.DEF_leg_18_2_L} />
            <primitive object={nodes.DEF_leg_18_3_L} />
            <primitive object={nodes.DEF_leg_18_4_L} />
            <primitive object={nodes.DEF_leg_18_5_L} />
            <primitive object={nodes.DEF_leg_18_1_R} />
            <primitive object={nodes.DEF_leg_18_2_R} />
            <primitive object={nodes.DEF_leg_18_3_R} />
            <primitive object={nodes.DEF_leg_18_4_R} />
            <primitive object={nodes.DEF_leg_18_5_R} />
            <primitive object={nodes.DEF_torso_19} />
            <primitive object={nodes.DEF_leg_19_1_L} />
            <primitive object={nodes.DEF_leg_19_2_L} />
            <primitive object={nodes.DEF_leg_19_3_L} />
            <primitive object={nodes.DEF_leg_19_4_L} />
            <primitive object={nodes.DEF_leg_19_5_L} />
            <primitive object={nodes.DEF_leg_19_1_R} />
            <primitive object={nodes.DEF_leg_19_2_R} />
            <primitive object={nodes.DEF_leg_19_3_R} />
            <primitive object={nodes.DEF_leg_19_4_R} />
            <primitive object={nodes.DEF_leg_19_5_R} />
            <primitive object={nodes.DEF_torso_20} />
            <primitive object={nodes.DEF_leg_20_1_L} />
            <primitive object={nodes.DEF_leg_20_2_L} />
            <primitive object={nodes.DEF_leg_20_3_L} />
            <primitive object={nodes.DEF_leg_20_4_L} />
            <primitive object={nodes.DEF_leg_20_5_L} />
            <primitive object={nodes.DEF_leg_20_1_R} />
            <primitive object={nodes.DEF_leg_20_2_R} />
            <primitive object={nodes.DEF_leg_20_3_R} />
            <primitive object={nodes.DEF_leg_20_4_R} />
            <primitive object={nodes.DEF_leg_20_5_R} />
            <primitive object={nodes.DEF_torso_21} />
            <primitive object={nodes.DEF_tail_1_L} />
            <primitive object={nodes.DEF_tail_2_L} />
            <primitive object={nodes.DEF_tail_3_L} />
            <primitive object={nodes.DEF_tail_4_L} />
            <primitive object={nodes.DEF_tail_1_R} />
            <primitive object={nodes.DEF_tail_2_R} />
            <primitive object={nodes.DEF_tail_3_R} />
            <primitive object={nodes.DEF_tail_4_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_1_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_2_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_3_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_4_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_5_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_6_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_7_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_8_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_9_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_10_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_11_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_12_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_13_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_14_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_15_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_16_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_17_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_18_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_19_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_20_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_tail_L} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_1_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_2_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_3_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_4_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_5_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_6_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_7_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_8_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_9_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_10_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_11_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_12_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_13_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_14_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_15_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_16_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_17_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_18_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_19_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_leg_20_R} />
            <primitive object={nodes.IK_VECTOR_CTRL_tail_R} />
            <primitive object={nodes.path_follow_1_L_L} />
            <primitive object={nodes.path_follow_3_L} />
            <primitive object={nodes.path_follow_4_L} />
            <primitive object={nodes.path_follow_5_L} />
            <primitive object={nodes.path_follow_6_L} />
            <primitive object={nodes.path_follow_7_L} />
            <primitive object={nodes.path_follow_8_L} />
            <primitive object={nodes.path_follow_9_L} />
            <primitive object={nodes.path_follow_10_L} />
            <primitive object={nodes.path_follow_11_L} />
            <primitive object={nodes.path_follow_12_L} />
            <primitive object={nodes.path_follow_13_L} />
            <primitive object={nodes.path_follow_14_L} />
            <primitive object={nodes.path_follow_15_L} />
            <primitive object={nodes.path_follow_16_L} />
            <primitive object={nodes.path_follow_17_L} />
            <primitive object={nodes.path_follow_18_L} />
            <primitive object={nodes.path_follow_19_L} />
            <primitive object={nodes.path_follow_2_L} />
            <primitive object={nodes.path_follow_20_L} />
            <primitive object={nodes.path_follow_1_L_R} />
            <primitive object={nodes.path_follow_3_R} />
            <primitive object={nodes.path_follow_4_R} />
            <primitive object={nodes.path_follow_5_R} />
            <primitive object={nodes.path_follow_6_R} />
            <primitive object={nodes.path_follow_7_R} />
            <primitive object={nodes.path_follow_8_R} />
            <primitive object={nodes.path_follow_9_R} />
            <primitive object={nodes.path_follow_10_R} />
            <primitive object={nodes.path_follow_11_R} />
            <primitive object={nodes.path_follow_12_R} />
            <primitive object={nodes.path_follow_13_R} />
            <primitive object={nodes.path_follow_14_R} />
            <primitive object={nodes.path_follow_15_R} />
            <primitive object={nodes.path_follow_16_R} />
            <primitive object={nodes.path_follow_17_R} />
            <primitive object={nodes.path_follow_18_R} />
            <primitive object={nodes.path_follow_19_R} />
            <primitive object={nodes.path_follow_2_R} />
            <primitive object={nodes.path_follow_20_R} />
            <primitive object={nodes.MCH_torso_1} />
            <primitive object={nodes.ROOT_scale} />
            <primitive object={nodes.CTRL_torso_1} />
            <primitive object={nodes.CTRL_torso_21} />
            <primitive object={nodes.CTRL_torso_6} />
            <primitive object={nodes.CTRL_torso_7} />
            <primitive object={nodes.CTRL_torso_8} />
            <primitive object={nodes.CTRL_torso_9} />
            <primitive object={nodes.CTRL_torso_10} />
            <primitive object={nodes.CTRL_torso_11} />
            <primitive object={nodes.CTRL_torso_12} />
            <primitive object={nodes.CTRL_torso_13} />
            <primitive object={nodes.CTRL_torso_14} />
            <primitive object={nodes.CTRL_torso_15} />
            <primitive object={nodes.CTRL_torso_16} />
            <primitive object={nodes.CTRL_torso_17} />
            <primitive object={nodes.CTRL_torso_18} />
            <primitive object={nodes.CTRL_torso_19} />
            <primitive object={nodes.CTRL_torso_20} />
            <primitive object={nodes.CTRL_torso_2} />
            <primitive object={nodes.CTRL_torso_3} />
            <primitive object={nodes.CTRL_torso_4} />
            <primitive object={nodes.CTRL_torso_5} />
          </group>
          <group
            name="WGT-IK_CTRL_leg_1_L"
            position={[0.24, 0, 0.475]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_3_L"
            position={[0.309, 0, 0.255]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_4_L"
            position={[0.309, 0, 0.124]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_5_L"
            position={[0.309, 0, -0.009]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_6_L"
            position={[0.309, 0, -0.13]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_7_L"
            position={[0.309, 0, -0.241]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_8_L"
            position={[0.309, 0, -0.373]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_9_L"
            position={[0.309, 0, -0.507]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_10_L"
            position={[0.309, 0, -0.628]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_11_L"
            position={[0.309, 0, -0.747]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_12_L"
            position={[0.309, 0, -0.878]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_13_L"
            position={[0.309, 0, -1.011]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_14_L"
            position={[0.309, 0, -1.133]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_15_L"
            position={[0.309, 0, -1.255]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_16_L"
            position={[0.309, 0, -1.386]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_17_L"
            position={[0.309, 0, -1.518]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_18_L"
            position={[0.309, 0, -1.651]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_19_L"
            position={[0.292, -0.001, -1.781]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_2_L"
            position={[0.288, -0.001, 0.365]}
            rotation={[-1.495, -Math.PI / 2, 0]}
            scale={0.021}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_1_L"
            position={[0.168, 0.171, 0.469]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_2_L"
            position={[0.206, 0.17, 0.369]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_3_L"
            position={[0.214, 0.17, 0.26]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_4_L"
            position={[0.215, 0.17, 0.129]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_5_L"
            position={[0.215, 0.17, -0.005]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_6_L"
            position={[0.215, 0.17, -0.126]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_7_L"
            position={[0.215, 0.17, -0.236]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_8_L"
            position={[0.215, 0.17, -0.369]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_9_L"
            position={[0.215, 0.17, -0.503]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_10_L"
            position={[0.215, 0.17, -0.623]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_11_L"
            position={[0.215, 0.17, -0.743]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_12_L"
            position={[0.215, 0.17, -0.874]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_13_L"
            position={[0.215, 0.17, -1.006]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_14_L"
            position={[0.215, 0.17, -1.129]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_15_L"
            position={[0.215, 0.17, -1.251]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_16_L"
            position={[0.215, 0.17, -1.382]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_17_L"
            position={[0.215, 0.17, -1.514]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_18_L"
            position={[0.215, 0.17, -1.646]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_19_L"
            position={[0.199, 0.171, -1.777]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_20_L"
            position={[0.185, 0.171, -1.898]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_tail_L"
            position={[0.081, 0.212, -2.32]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.068}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_1_R"
            position={[-0.168, 0.171, 0.469]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_2_R"
            position={[-0.206, 0.17, 0.369]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_3_R"
            position={[-0.214, 0.17, 0.26]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_4_R"
            position={[-0.215, 0.17, 0.129]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_5_R"
            position={[-0.215, 0.17, -0.005]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_6_R"
            position={[-0.215, 0.17, -0.126]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_7_R"
            position={[-0.215, 0.17, -0.236]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_8_R"
            position={[-0.215, 0.17, -0.369]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_9_R"
            position={[-0.215, 0.17, -0.503]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_10_R"
            position={[-0.215, 0.17, -0.623]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_11_R"
            position={[-0.215, 0.17, -0.743]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_12_R"
            position={[-0.215, 0.17, -0.874]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_13_R"
            position={[-0.215, 0.17, -1.006]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_14_R"
            position={[-0.215, 0.17, -1.129]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_15_R"
            position={[-0.215, 0.17, -1.251]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_16_R"
            position={[-0.215, 0.17, -1.382]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_17_R"
            position={[-0.215, 0.17, -1.514]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_18_R"
            position={[-0.215, 0.17, -1.646]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_19_R"
            position={[-0.199, 0.171, -1.777]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_leg_20_R"
            position={[-0.185, 0.171, -1.898]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          />
          <group
            name="WGT-IK_VECTOR_CTRL_tail_R"
            position={[-0.081, 0.212, -2.32]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.068}
          />
          <group
            name="WGT-IK_CTRL_tail_L"
            position={[0.122, 0.048, -2.529]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.051}
          />
          <group
            name="WGT-CTRL_torso_21"
            position={[0, 0.094, -2.022]}
            scale={0.053}
          />
          <group
            name="WGT-CTRL_torso_1"
            position={[0, 0.094, 0.457]}
            scale={0.065}
          />
          <group
            name="WGT-CTRL_torso_2"
            position={[0, 0.094, 0.368]}
            scale={0.076}
          />
          <group
            name="WGT-CTRL_torso_3"
            position={[0, 0.094, 0.256]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_4"
            position={[0, 0.094, 0.125]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_5"
            position={[0, 0.094, -0.006]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_6"
            position={[0, 0.094, -0.127]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_7"
            position={[0, 0.094, -0.244]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_8"
            position={[0, 0.093, -0.374]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_9"
            position={[0, 0.094, -0.505]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_10"
            position={[0, 0.094, -0.626]}
            scale={0.108}
          />
          <group
            name="WGT-CTRL_torso_11"
            position={[0, 0.094, -0.748]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_12"
            position={[0, 0.094, -0.878]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_13"
            position={[0, 0.094, -1.009]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_14"
            position={[0, 0.094, -1.126]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_15"
            position={[0, 0.094, -1.256]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_16"
            position={[0, 0.094, -1.387]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_17"
            position={[0, 0.094, -1.518]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_18"
            position={[0, 0.094, -1.646]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_19"
            position={[0, 0.094, -1.777]}
            scale={0.1}
          />
          <group
            name="WGT-CTRL_torso_20"
            position={[0, 0.094, -1.899]}
            scale={0.081}
          />
          <group
            name="WGT-CTRL_head"
            position={[0, 0.118, 0.546]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.085}
          />
          <group
            name="WGT-IK_CTRL_leg_20_L"
            position={[0.258, 0.002, -1.903]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_1_R"
            position={[-0.24, 0, 0.475]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_3_R"
            position={[-0.309, 0, 0.255]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_4_R"
            position={[-0.309, 0, 0.124]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_5_R"
            position={[-0.309, 0, -0.009]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_6_R"
            position={[-0.309, 0, -0.13]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_7_R"
            position={[-0.309, 0, -0.241]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_8_R"
            position={[-0.309, 0, -0.373]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_9_R"
            position={[-0.309, 0, -0.507]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_10_R"
            position={[-0.309, 0, -0.628]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_11_R"
            position={[-0.309, 0, -0.747]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_12_R"
            position={[-0.309, 0, -0.878]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_13_R"
            position={[-0.309, 0, -1.011]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_14_R"
            position={[-0.309, 0, -1.133]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_15_R"
            position={[-0.309, 0, -1.255]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_16_R"
            position={[-0.309, 0, -1.386]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_17_R"
            position={[-0.309, 0, -1.518]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_18_R"
            position={[-0.309, 0, -1.651]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_19_R"
            position={[-0.292, -0.001, -1.781]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_leg_2_R"
            position={[-0.288, -0.001, 0.365]}
            rotation={[-1.495, Math.PI / 2, 0]}
            scale={0.021}
          />
          <group
            name="WGT-IK_CTRL_leg_20_R"
            position={[-0.258, 0.002, -1.903]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.027}
          />
          <group
            name="WGT-IK_CTRL_tail_R"
            position={[-0.122, 0.048, -2.529]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.051}
          />
          <group
            name="WGT-CTRL_nail_1_L"
            position={[0.087, 0.072, 0.534]}
            rotation={[-2.934, -0.111, 0.591]}
            scale={0.091}
          />
          <group
            name="WGT-CTRL_nail_2_L"
            position={[0.1, 0.047, 0.654]}
            rotation={[-2.951, 0.834, -1.996]}
            scale={0.06}
          />
          <group
            name="WGT-FK_CTRL_tendril_1_L"
            position={[0.021, 0.108, 0.698]}
            rotation={[3.028, -1.299, 2.992]}
            scale={0.071}
          />
          <group
            name="WGT-FK_CTRL_tendril_2_L"
            position={[0.119, 0.111, 0.725]}
            rotation={[-3.12, -1.322, -3.114]}
            scale={0.067}
          />
          <group
            name="WGT-FK_CTRL_tendril_3_L"
            position={[0.212, 0.11, 0.749]}
            rotation={[3.14, -1.309, 3.139]}
            scale={0.055}
          />
          <group
            name="WGT-FK_CTRL_tendril_4_L"
            position={[0.289, 0.11, 0.769]}
            rotation={[3.131, -1.303, 3.128]}
            scale={0.049}
          />
          <group
            name="WGT-FK_CTRL_tendril_5_L"
            position={[0.356, 0.11, 0.788]}
            rotation={[-3.087, -1.316, -3.071]}
            scale={0.041}
          />
          <group
            name="WGT-FK_CTRL_tendril_6_L"
            position={[0.413, 0.11, 0.802]}
            rotation={[-3.123, -1.325, -3.118]}
            scale={0.029}
          />
          <group
            name="WGT-FK_CTRL_tendril_7_L"
            position={[0.454, 0.109, 0.813]}
            rotation={[3.015, -1.281, 2.972]}
            scale={0.01}
          />
          <group
            name="WGT-IK_CTRL_hand_L"
            position={[0.008, 0.055, 0.685]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.009}
          />
          <group
            name="WGT-CTRL_nail_1_R"
            position={[-0.087, 0.072, 0.534]}
            rotation={[-2.934, 0.111, -0.591]}
            scale={0.091}
          />
          <group
            name="WGT-CTRL_nail_2_R"
            position={[-0.1, 0.047, 0.654]}
            rotation={[-2.951, -0.834, 1.996]}
            scale={0.06}
          />
          <group
            name="WGT-IK_CTRL_hand_R"
            position={[-0.008, 0.055, 0.685]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.009}
          />
          <group
            name="WGT-FK_CTRL_tendril_2_R"
            position={[-0.119, 0.111, 0.725]}
            rotation={[-3.12, 1.322, 3.114]}
            scale={0.067}
          />
          <group
            name="WGT-FK_CTRL_tendril_3_R"
            position={[-0.212, 0.11, 0.749]}
            rotation={[3.14, 1.309, -3.139]}
            scale={0.055}
          />
          <group
            name="WGT-FK_CTRL_tendril_4_R"
            position={[-0.289, 0.11, 0.769]}
            rotation={[3.131, 1.303, -3.128]}
            scale={0.049}
          />
          <group
            name="WGT-FK_CTRL_tendril_5_R"
            position={[-0.356, 0.11, 0.788]}
            rotation={[-3.087, 1.316, 3.071]}
            scale={0.041}
          />
          <group
            name="WGT-FK_CTRL_tendril_6_R"
            position={[-0.413, 0.11, 0.802]}
            rotation={[-3.123, 1.325, 3.118]}
            scale={0.029}
          />
          <group
            name="WGT-FK_CTRL_tendril_7_R"
            position={[-0.454, 0.109, 0.813]}
            rotation={[3.015, 1.281, -2.972]}
            scale={0.01}
          />
          <group
            name="WGT-FK_CTRL_tendril_1_R"
            position={[-0.021, 0.108, 0.698]}
            rotation={[3.028, 1.299, -2.992]}
            scale={0.071}
          />
          <group
            name="WGT-PROPERTIES"
            position={[0, 0.226, 0.256]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.099}
          />
          <group
            name="WGT-TWEAK_torso_21"
            position={[0, 0.094, -2.022]}
            scale={0.03}
          />
          <group
            name="WGT-TWEAK_torso_1"
            position={[0, 0.094, 0.457]}
            scale={0.049}
          />
          <group
            name="WGT-TWEAK_nail_1_R"
            position={[-0.087, 0.072, 0.534]}
            rotation={[-2.934, 0.111, -0.591]}
            scale={0.061}
          />
          <group
            name="WGT-TWEAK_nail_2_R"
            position={[-0.1, 0.047, 0.654]}
            rotation={[-2.951, -0.834, 1.996]}
            scale={0.04}
          />
          <group
            name="WGT-TWEAK_nail_1_L"
            position={[0.087, 0.072, 0.534]}
            rotation={[-2.934, -0.111, 0.591]}
            scale={0.061}
          />
          <group
            name="WGT-TWEAK_nail_2_L"
            position={[0.1, 0.047, 0.654]}
            rotation={[-2.951, 0.834, -1.996]}
            scale={0.04}
          />
          <group
            name="WGT-TWEAK_head"
            position={[0, 0.118, 0.546]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.063}
          />
          <group
            name="WGT-TWEAK_tendril_1_L"
            position={[0.021, 0.108, 0.698]}
            rotation={[3.028, -1.299, 2.992]}
            scale={0.048}
          />
          <group
            name="WGT-TWEAK_tendril_2_L"
            position={[0.119, 0.111, 0.725]}
            rotation={[-3.12, -1.322, -3.114]}
            scale={0.045}
          />
          <group
            name="WGT-TWEAK_tendril_3_L"
            position={[0.212, 0.11, 0.749]}
            rotation={[3.14, -1.309, 3.139]}
            scale={0.037}
          />
          <group
            name="WGT-TWEAK_tendril_4_L"
            position={[0.289, 0.11, 0.769]}
            rotation={[3.131, -1.303, 3.128]}
            scale={0.033}
          />
          <group
            name="WGT-TWEAK_tendril_5_L"
            position={[0.356, 0.11, 0.788]}
            rotation={[-3.087, -1.316, -3.071]}
            scale={0.028}
          />
          <group
            name="WGT-TWEAK_tendril_6_L"
            position={[0.413, 0.11, 0.802]}
            rotation={[-3.123, -1.325, -3.118]}
            scale={0.02}
          />
          <group
            name="WGT-TWEAK_tendril_7_L"
            position={[0.454, 0.109, 0.813]}
            rotation={[3.015, -1.281, 2.972]}
            scale={0.007}
          />
          <group
            name="WGT-TWEAK_tendril_1_R"
            position={[-0.021, 0.108, 0.698]}
            rotation={[3.028, 1.299, -2.992]}
            scale={0.048}
          />
          <group
            name="WGT-TWEAK_tendril_2_R"
            position={[-0.119, 0.111, 0.725]}
            rotation={[-3.12, 1.322, 3.114]}
            scale={0.045}
          />
          <group
            name="WGT-TWEAK_tendril_3_R"
            position={[-0.212, 0.11, 0.749]}
            rotation={[3.14, 1.309, -3.139]}
            scale={0.037}
          />
          <group
            name="WGT-TWEAK_tendril_4_R"
            position={[-0.289, 0.11, 0.769]}
            rotation={[3.131, 1.303, -3.128]}
            scale={0.033}
          />
          <group
            name="WGT-TWEAK_tendril_5_R"
            position={[-0.356, 0.11, 0.788]}
            rotation={[-3.087, 1.316, 3.071]}
            scale={0.028}
          />
          <group
            name="WGT-TWEAK_tendril_6_R"
            position={[-0.413, 0.11, 0.802]}
            rotation={[-3.123, 1.325, 3.118]}
            scale={0.02}
          />
          <group
            name="WGT-TWEAK_tendril_7_R"
            position={[-0.454, 0.109, 0.813]}
            rotation={[3.015, 1.281, -2.972]}
            scale={0.007}
          />
          <group
            name="WGT-TWEAK_torso_2"
            position={[0, 0.094, 0.368]}
            scale={0.042}
          />
          <group
            name="WGT-TWEAK_torso_3"
            position={[0, 0.094, 0.256]}
            scale={0.056}
          />
          <group
            name="WGT-TWEAK_torso_4"
            position={[0, 0.094, 0.125]}
            scale={0.056}
          />
          <group
            name="WGT-TWEAK_torso_5"
            position={[0, 0.094, -0.006]}
            scale={0.055}
          />
          <group
            name="WGT-TWEAK_torso_6"
            position={[0, 0.094, -0.127]}
            scale={0.055}
          />
          <group
            name="WGT-TWEAK_torso_7"
            position={[0, 0.094, -0.244]}
            scale={0.056}
          />
          <group
            name="WGT-TWEAK_torso_8"
            position={[0, 0.093, -0.374]}
            scale={0.056}
          />
          <group
            name="WGT-TWEAK_torso_9"
            position={[0, 0.094, -0.505]}
            scale={0.055}
          />
          <group
            name="WGT-TWEAK_torso_10"
            position={[0, 0.095, -0.626]}
            scale={0.06}
          />
          <group
            name="WGT-TWEAK_torso_11"
            position={[0, 0.093, -0.748]}
            scale={0.056}
          />
          <group
            name="WGT-TWEAK_torso_12"
            position={[0, 0.094, -0.878]}
            scale={0.056}
          />
          <group
            name="WGT-TWEAK_torso_13"
            position={[0, 0.094, -1.009]}
            scale={0.055}
          />
          <group
            name="WGT-TWEAK_torso_14"
            position={[0, 0.094, -1.126]}
            scale={0.055}
          />
          <group
            name="WGT-TWEAK_torso_15"
            position={[0, 0.094, -1.256]}
            scale={0.056}
          />
          <group
            name="WGT-TWEAK_torso_16"
            position={[0, 0.094, -1.386]}
            scale={0.056}
          />
          <group
            name="WGT-TWEAK_torso_17"
            position={[0, 0.094, -1.518]}
            scale={0.056}
          />
          <group
            name="WGT-TWEAK_torso_18"
            position={[0, 0.094, -1.646]}
            scale={0.055}
          />
          <group
            name="WGT-TWEAK_torso_19"
            position={[0, 0.094, -1.777]}
            scale={0.055}
          />
          <group
            name="WGT-TWEAK_torso_20"
            position={[0, 0.094, -1.899]}
            scale={0.045}
          />
          <group name="WGT-ROOT" position={[0, 0.005, -0.001]} scale={0.01} />
          <group name="leg_collide_3_L" position={[0.031, 0.005, 0.024]} />
          <group name="leg_collide_2_L" position={[0.029, 0.004, 0.044]} />
          <group name="leg_collide_1_L" position={[0.024, 0, 0.05]} />
          <group name="leg_collide_4_L" position={[0.031, 0, -0.001]} />
          <group name="leg_collide_5_L" position={[0.031, 0, -0.001]} />
          <group name="leg_collide_6_L" position={[0.031, 0, -0.003]} />
          <group
            name="leg_collide_7_L"
            position={[0.031, 0.004, -0.02]}
            rotation={[0.004, 0, 0]}
          />
          <group
            name="leg_collide_8_L"
            position={[0.031, 0.003, -0.047]}
            rotation={[-0.004, 0, 0]}
          />
          <group name="leg_collide_9_L" position={[0.031, 0, -0.054]} />
          <group name="leg_collide_10_L" position={[0.031, 0, -0.055]} />
          <group name="leg_collide_11_L" position={[0.031, 0.004, -0.07]} />
          <group name="leg_collide_12_L" position={[0.031, 0.005, -0.094]} />
          <group name="leg_collide_13_L" position={[0.031, 0, -0.108]} />
          <group name="leg_collide_14_L" position={[0.031, 0, -0.109]} />
          <group name="leg_collide_15_L" position={[0.031, 0.003, -0.116]} />
          <group name="leg_collide_16_L" position={[0.031, 0.005, -0.141]} />
          <group name="leg_collide_17_L" position={[0.031, 0, -0.164]} />
          <group name="leg_collide_18_L" position={[0.031, 0, -0.164]} />
          <group name="leg_collide_19_L" position={[0.029, 0.001, -0.166]} />
          <group name="leg_collide_20_L" position={[0.026, 0.005, -0.191]} />
          <group
            name="LEG_PATH_9_L"
            position={[0.031, 0, -0.051]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_8_L"
            position={[0.031, 0, -0.037]}
            rotation={[-0.004, 0, 0]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_7_L"
            position={[0.031, 0, -0.024]}
            rotation={[0.004, 0, 0]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_6_L"
            position={[0.031, 0, -0.013]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_5_L"
            position={[0.031, 0, -0.001]}
            scale={0.1}
          />
          <group name="LEG_PATH_4_L" position={[0.031, 0, 0.012]} scale={0.1} />
          <group name="LEG_PATH_3_L" position={[0.031, 0, 0.025]} scale={0.1} />
          <group name="LEG_PATH_2_L" position={[0.029, 0, 0.037]} scale={0.1} />
          <group
            name="LEG_PATH_20_L"
            position={[0.026, 0, -0.19]}
            scale={0.1}
          />
          <group name="LEG_PATH_1_L" position={[0.024, 0, 0.047]} scale={0.1} />
          <group
            name="LEG_PATH_19_L"
            position={[0.029, 0, -0.178]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_18_L"
            position={[0.031, 0, -0.165]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_17_L"
            position={[0.031, 0, -0.152]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_16_L"
            position={[0.031, 0, -0.139]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_15_L"
            position={[0.031, 0, -0.125]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_14_L"
            position={[0.031, 0, -0.113]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_13_L"
            position={[0.031, 0, -0.101]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_12_L"
            position={[0.031, 0, -0.088]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_11_L"
            position={[0.031, 0, -0.076]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_10_L"
            position={[0.031, 0, -0.063]}
            scale={0.1}
          />
          <group name="leg_collide_3_R" position={[-0.031, 0, 0.033]} />
          <group name="leg_collide_2_R" position={[-0.029, 0, 0.033]} />
          <group name="leg_collide_1_R" position={[-0.024, 0.002, 0.043]} />
          <group name="leg_collide_4_R" position={[-0.031, 0.004, 0.019]} />
          <group name="leg_collide_5_R" position={[-0.031, 0.005, -0.006]} />
          <group name="leg_collide_6_R" position={[-0.031, 0, -0.022]} />
          <group
            name="leg_collide_7_R"
            position={[-0.031, 0, -0.023]}
            rotation={[0.004, 0, 0]}
          />
          <group
            name="leg_collide_8_R"
            position={[-0.031, 0.002, -0.027]}
            rotation={[-0.004, 0, 0]}
          />
          <group name="leg_collide_9_R" position={[-0.031, 0.005, -0.052]} />
          <group name="leg_collide_10_R" position={[-0.031, 0.001, -0.074]} />
          <group name="leg_collide_11_R" position={[-0.031, 0, -0.076]} />
          <group name="leg_collide_12_R" position={[-0.031, 0, -0.077]} />
          <group name="leg_collide_13_R" position={[-0.031, 0.005, -0.099]} />
          <group name="leg_collide_14_R" position={[-0.031, 0.002, -0.123]} />
          <group name="leg_collide_15_R" position={[-0.031, 0, -0.129]} />
          <group name="leg_collide_16_R" position={[-0.031, 0, -0.13]} />
          <group name="leg_collide_17_R" position={[-0.031, 0.004, -0.145]} />
          <group name="leg_collide_18_R" position={[-0.031, 0.004, -0.17]} />
          <group name="leg_collide_19_R" position={[-0.029, 0, -0.186]} />
          <group name="leg_collide_20_R" position={[-0.026, 0, -0.184]} />
          <group
            name="LEG_PATH_9_R"
            position={[-0.031, 0, -0.051]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_8_R"
            position={[-0.031, 0, -0.037]}
            rotation={[-0.004, 0, 0]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_7_R"
            position={[-0.031, 0, -0.024]}
            rotation={[0.004, 0, 0]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_6_R"
            position={[-0.031, 0, -0.013]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_5_R"
            position={[-0.031, 0, -0.001]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_4_R"
            position={[-0.031, 0, 0.012]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_3_R"
            position={[-0.031, 0, 0.025]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_2_R"
            position={[-0.029, 0, 0.037]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_20_R"
            position={[-0.026, 0, -0.19]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_1_R"
            position={[-0.024, 0, 0.047]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_19_R"
            position={[-0.029, 0, -0.178]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_18_R"
            position={[-0.031, 0, -0.165]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_17_R"
            position={[-0.031, 0, -0.152]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_16_R"
            position={[-0.031, 0, -0.139]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_15_R"
            position={[-0.031, 0, -0.125]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_14_R"
            position={[-0.031, 0, -0.113]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_13_R"
            position={[-0.031, 0, -0.101]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_12_R"
            position={[-0.031, 0, -0.088]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_11_R"
            position={[-0.031, 0, -0.076]}
            scale={0.1}
          />
          <group
            name="LEG_PATH_10_R"
            position={[-0.031, 0, -0.063]}
            scale={0.1}
          />
        </group>
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/models/centipede.glb");
