/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rescue3D Assets (https://sketchfab.com/rescue3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chainsaw-8d1c55a879b046ba940414f5ee57f401
Title: Chainsaw
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/chainsaw.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="262252b914884a0ab864d9ff4feb213afbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="RootNode">
              <group name="Chainsaw01">
                <group name="Object_4" position={[0, -17.268, 9.691]}>
                  <mesh
                    name="Chainsaw01_Chainsaw01_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chainsaw01_Chainsaw01_0.geometry}
                    material={materials.Chainsaw01}
                  />
                  <mesh
                    name="Chainsaw01_Chainsaw01_Alpha_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chainsaw01_Chainsaw01_Alpha_0.geometry}
                    material={materials.Chainsaw01_Alpha}
                  />
                  <mesh
                    name="Chainsaw01_Chainsaw01_Chain_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chainsaw01_Chainsaw01_Chain_0.geometry}
                    material={materials.Chainsaw01_Chain}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/chainsaw.glb");
