/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lightningx (https://sketchfab.com/Lightningx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dolphin-56348c155ed44af7bbda861bb30b65e4
Title: Dolphin
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/dolphin.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="8dc8f60d94f244c9962bd7fa5113ef84fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="RootNode">
              <group name="pSphere2">
                <mesh
                  name="pSphere2_lambert1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.pSphere2_lambert1_0.geometry}
                  material={materials.lambert1}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/dolphin.glb");
