/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: arun1232 (https://sketchfab.com/arun1232)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/excavator-952e7ad4a3ba46d7ad977af244a832be
Title: Excavator
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/excavator.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="82772096b7434f88891720aaa62d6367fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode">
              <group name="Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body_BodyPaint1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body_BodyPaint1_0.geometry}
                  material={materials.BodyPaint1}
                />
              </group>
              <group
                name="FBucket"
                position={[0, -8.227, 430.165]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  name="FBucket_BodyPaint1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FBucket_BodyPaint1_0.geometry}
                  material={materials.BodyPaint1}
                />
              </group>
              <group name="FArm" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="FArm_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FArm_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="BBucket"
                position={[0, 62.653, -628.828]}
                scale={[30.989, 100, 100]}
              >
                <mesh
                  name="BBucket_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BBucket_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="BFemur"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur_BodyPaint1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur_BodyPaint1_0.geometry}
                  material={materials.BodyPaint1}
                />
              </group>
              <group
                name="BArm"
                position={[0, 290.685, -317.699]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.539}
              >
                <mesh
                  name="BArm_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BArm_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="FWheel"
                position={[138.515, -46.592, 242.58]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[50.301, 50.301, 21.628]}
              >
                <mesh
                  name="FWheel_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FWheel_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="Cylinder001"
                position={[164.107, -40.684, 242.718]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={1.853}
              >
                <mesh
                  name="Cylinder001_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder001_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="FWheelLHub"
                position={[138.515, -46.592, 242.58]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[50.301, 50.301, 21.628]}
              >
                <mesh
                  name="FWheelLHub_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FWheelLHub_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group name="Body001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body001_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body001_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group name="Body002" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body002_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body002_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group name="Body003" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body003_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body003_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="FBucket001"
                position={[0, -8.227, 430.165]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  name="FBucket001_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FBucket001_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="FArm001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="FArm001_Steel_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FArm001_Steel_0.geometry}
                  material={materials.Steel}
                />
              </group>
              <group name="FArm002" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="FArm002_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FArm002_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="FArm003" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="FArm003_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FArm003_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group name="FArm004" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="FArm004_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FArm004_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group name="Body004" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body004_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body004_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="Body005" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body005_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body005_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="Body006" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body006_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body006_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="Body007" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body007_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body007_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="Body008" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body008_BodyPaint1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body008_BodyPaint1_0.geometry}
                  material={materials.BodyPaint1}
                />
              </group>
              <group name="Body009" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body009_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body009_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group name="Body010" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body010_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body010_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group name="Body011" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body011_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body011_Glass_0.geometry}
                  material={materials.Glass}
                />
              </group>
              <group name="Body012" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body012_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body012_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="Body013" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body013_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body013_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="Body014" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body014_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body014_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="Body015" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body015_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body015_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group name="Body016" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body016_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body016_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group name="Body017" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body017_whiteLight_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body017_whiteLight_0.geometry}
                  material={materials.whiteLight}
                />
              </group>
              <group name="Body018" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body018_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body018_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="BFemur001"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur001_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur001_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="BFemur002"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur002_Steel_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur002_Steel_0.geometry}
                  material={materials.Steel}
                />
              </group>
              <group
                name="BFemur003"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur003_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur003_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group
                name="BFemur004"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur004_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur004_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="BFemur005"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur005_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur005_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="BFemur006"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur006_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur006_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="BFemur007"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur007_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur007_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="BFemur008"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur008_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur008_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="BFemur009"
                position={[0, 0, -238.846]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={41.441}
              >
                <mesh
                  name="BFemur009_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BFemur009_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group
                name="BArm001"
                position={[0, 290.685, -317.699]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.539}
              >
                <mesh
                  name="BArm001_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BArm001_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="BArm002"
                position={[0, 290.685, -317.699]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.539}
              >
                <mesh
                  name="BArm002_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BArm002_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="BArm003"
                position={[0, 290.685, -317.699]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.539}
              >
                <mesh
                  name="BArm003_BodyPaint1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BArm003_BodyPaint1_0.geometry}
                  material={materials.BodyPaint1}
                />
              </group>
              <group
                name="BArm004"
                position={[0, 290.685, -317.699]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.539}
              >
                <mesh
                  name="BArm004_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BArm004_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group
                name="BArm005"
                position={[0, 290.685, -317.699]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.539}
              >
                <mesh
                  name="BArm005_BodyPaint1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BArm005_BodyPaint1_0.geometry}
                  material={materials.BodyPaint1}
                />
              </group>
              <group
                name="BArm006"
                position={[0, 290.685, -317.699]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.539}
              >
                <mesh
                  name="BArm006_Steel_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BArm006_Steel_0.geometry}
                  material={materials.Steel}
                />
              </group>
              <group
                name="BArm007"
                position={[0, 290.685, -317.699]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.539}
              >
                <mesh
                  name="BArm007_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BArm007_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group
                name="BArm008"
                position={[0, 290.685, -317.699]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.539}
              >
                <mesh
                  name="BArm008_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BArm008_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group
                name="BBucket001"
                position={[0, 62.653, -628.828]}
                scale={[30.989, 100, 100]}
              >
                <mesh
                  name="BBucket001_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BBucket001_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="BBucket002"
                position={[0, 62.653, -628.828]}
                scale={[30.989, 100, 100]}
              >
                <mesh
                  name="BBucket002_BodyPaint1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.BBucket002_BodyPaint1_0.geometry}
                  material={materials.BodyPaint1}
                />
              </group>
              <group
                name="FBucket002"
                position={[0, -8.227, 430.165]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  name="FBucket002_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FBucket002_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="FBucket003"
                position={[0, -8.227, 430.165]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  name="FBucket003_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FBucket003_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group name="Body019" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body019_whiteLight_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body019_whiteLight_0.geometry}
                  material={materials.whiteLight}
                />
              </group>
              <group name="Body020" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body020_RedLight_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body020_RedLight_0.geometry}
                  material={materials.RedLight}
                />
              </group>
              <group name="Body021" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body021_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body021_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group name="Body022" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body022_whiteLight_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body022_whiteLight_0.geometry}
                  material={materials.whiteLight}
                />
              </group>
              <group name="Body023" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body023_RedLight_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body023_RedLight_0.geometry}
                  material={materials.RedLight}
                />
              </group>
              <group name="Body024" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body024_YellowLight_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body024_YellowLight_0.geometry}
                  material={materials.YellowLight}
                />
              </group>
              <group name="Body025" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body025_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body025_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group name="Body026" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  name="Body026_whiteLight_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body026_whiteLight_0.geometry}
                  material={materials.whiteLight}
                />
              </group>
              <group
                name="FWheel001"
                position={[195.46, -0.008, -87.808]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[93.65, 93.65, 35.525]}
              >
                <mesh
                  name="FWheel001_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FWheel001_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="RWheel002"
                position={[-198.172, -0.008, -87.808]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[93.65, 93.65, 35.525]}
              >
                <mesh
                  name="RWheel002_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RWheel002_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="FWheel003"
                position={[-138.297, -46.592, 242.58]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[50.301, 50.301, 21.628]}
              >
                <mesh
                  name="FWheel003_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FWheel003_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="Steer"
                position={[-163.642, -40.684, 242.718]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={1.853}
              >
                <mesh
                  name="Steer_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Steer_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="FWheelAxle"
                position={[3.138, -46.395, 241.049]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[13.216, 13.216, 126.652]}
              >
                <mesh
                  name="FWheelAxle_BodyPaint1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FWheelAxle_BodyPaint1_0.geometry}
                  material={materials.BodyPaint1}
                />
              </group>
              <group
                name="Torus"
                position={[40.842, 124.379, 21.83]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={24.52}
              >
                <mesh
                  name="Torus_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="GearLever"
                position={[-0.012, 56.562, 39.53]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[8.89, 8.89, 2.026]}
              >
                <mesh
                  name="GearLever_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.GearLever_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="ArmControl1"
                position={[-25.158, 100.416, -167.937]}
                rotation={[-Math.PI / 2, 0, 2.709]}
                scale={[8.89, 8.89, 2.026]}
              >
                <mesh
                  name="ArmControl1_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.ArmControl1_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="ArmControl2"
                position={[-0.286, 100.416, -167.937]}
                rotation={[-Math.PI / 2, 0, -2.243]}
                scale={[8.89, 8.89, 2.026]}
              >
                <mesh
                  name="ArmControl2_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.ArmControl2_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="knob4"
                position={[-14.775, 63.527, 57.798]}
                rotation={[-Math.PI / 2, -0.068, 0]}
                scale={[8.453, 1.224, 3.786]}
              >
                <mesh
                  name="knob4_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.knob4_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="RLiver"
                position={[-35.563, 68.599, 57.798]}
                rotation={[-Math.PI / 2, -0.068, 0]}
                scale={[8.584, 1.224, 10.6]}
              >
                <mesh
                  name="RLiver_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RLiver_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="knob"
                position={[-55.192, 60.803, 57.798]}
                rotation={[-Math.PI / 2, -0.068, 0]}
                scale={[8.453, 1.224, 3.786]}
              >
                <mesh
                  name="knob_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.knob_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="Knob1"
                position={[-55.296, 78.459, 57.798]}
                rotation={[-Math.PI / 2, -0.068, 0]}
                scale={[8.453, 1.224, 3.786]}
              >
                <mesh
                  name="Knob1_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Knob1_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="knob2"
                position={[-73.765, 76.808, 57.798]}
                rotation={[-Math.PI / 2, -0.068, 0]}
                scale={[8.453, 1.224, 3.786]}
              >
                <mesh
                  name="knob2_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.knob2_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="knob3"
                position={[80.112, 60.214, 64.393]}
                rotation={[-Math.PI / 2, -0.068, 0]}
                scale={[8.453, 1.224, 3.786]}
              >
                <mesh
                  name="knob3_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.knob3_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="FGlass"
                position={[0, 168.88, 110.748]}
                rotation={[-1.741, 0, 0]}
                scale={[100, 2.279, 67.294]}
              >
                <mesh
                  name="FGlass_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FGlass_Glass_0.geometry}
                  material={materials.Glass}
                />
              </group>
              <group
                name="Cube"
                position={[0, 317.587, -141.518]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[100, 1.758, 100]}
              >
                <mesh
                  name="Cube_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_Glass_0.geometry}
                  material={materials.Glass}
                />
              </group>
              <group
                name="Cylinder002"
                position={[111.368, 30.339, 176.219]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[7.408, 7.408, 16.085]}
              >
                <mesh
                  name="Cylinder002_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder002_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="Cylinder000"
                position={[-110.606, 28.594, 192.312]}
                rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                scale={[7.408, 7.408, 16.085]}
              >
                <mesh
                  name="Cylinder000_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder000_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="Poka"
                position={[-75.489, 106.732, 142.184]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[12.953, 12.953, 6.51]}
              >
                <mesh
                  name="Poka_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Poka_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="Cube001"
                position={[114.653, 58.097, -178.157]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[8.194, 23.398, 23.398]}
              >
                <mesh
                  name="Cube001_BwonMat_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube001_BwonMat_0.geometry}
                  material={materials.BwonMat}
                />
              </group>
              <group
                name="Cube002"
                position={[134.13, 58.097, -178.157]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[8.194, 23.398, 23.398]}
              >
                <mesh
                  name="Cube002_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube002_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="Chain"
                position={[130.458, 27.862, -204.979]}
                rotation={[Math.PI, 0, Math.PI / 2]}
                scale={[5.396, 2.949, 3.914]}
              >
                <mesh
                  name="Chain_Steel_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chain_Steel_0.geometry}
                  material={materials.Steel}
                />
              </group>
              <group
                name="Chain001"
                position={[-125.358, 27.862, -204.979]}
                rotation={[Math.PI, 0, Math.PI / 2]}
                scale={[5.396, 2.949, 3.914]}
              >
                <mesh
                  name="Chain001_Steel_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chain001_Steel_0.geometry}
                  material={materials.Steel}
                />
              </group>
              <group
                name="Chain002"
                position={[87.114, 205.394, -148.243]}
                rotation={[Math.PI, 0, Math.PI / 2]}
                scale={[5.396, 2.949, 3.914]}
              >
                <mesh
                  name="Chain002_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chain002_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="Chain003"
                position={[-87.285, 205.394, -148.243]}
                rotation={[Math.PI, 0, Math.PI / 2]}
                scale={[5.396, 2.949, 3.914]}
              >
                <mesh
                  name="Chain003_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chain003_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="Chain004"
                position={[50.522, -18.736, 263.984]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[5.396, 2.949, 3.914]}
              >
                <mesh
                  name="Chain004_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chain004_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="Chain005"
                position={[-42.015, -18.736, 263.984]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[5.396, 2.949, 3.914]}
              >
                <mesh
                  name="Chain005_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chain005_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="Cube003"
                position={[-88.646, 293.667, -94.932]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[4.065, 8.658, 8.658]}
              >
                <mesh
                  name="Cube003_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube003_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="Chain006"
                position={[139.197, 27.443, 73.964]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[5.396, 2.949, 3.914]}
              >
                <mesh
                  name="Chain006_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chain006_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="Chain007"
                position={[-135.739, 27.443, 73.964]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[5.396, 2.949, 3.914]}
              >
                <mesh
                  name="Chain007_BlackMetal_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chain007_BlackMetal_0.geometry}
                  material={materials.BlackMetal}
                />
              </group>
              <group
                name="FWheelRHub"
                position={[-138.297, -46.592, 242.58]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[50.301, 50.301, 21.628]}
              >
                <mesh
                  name="FWheelRHub_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FWheelRHub_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="RWheelRhub"
                position={[-198.172, -0.008, -87.808]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[93.65, 93.65, 35.525]}
              >
                <mesh
                  name="RWheelRhub_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RWheelRhub_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="RWheelLHub"
                position={[195.46, -0.008, -87.808]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[93.65, 93.65, 35.525]}
              >
                <mesh
                  name="RWheelLHub_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.RWheelLHub_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="Torus001"
                position={[40.842, 124.379, 21.83]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={24.52}
              >
                <mesh
                  name="Torus001_Rubber_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus001_Rubber_0.geometry}
                  material={materials.Rubber}
                />
              </group>
              <group
                name="Poka001"
                position={[-75.489, 106.732, 142.184]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[12.953, 12.953, 6.51]}
              >
                <mesh
                  name="Poka001_BodyPaint2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Poka001_BodyPaint2_0.geometry}
                  material={materials.BodyPaint2}
                />
              </group>
              <group
                name="Cylinder003"
                position={[236.277, 9.136, -88.613]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={3.085}
              >
                <mesh
                  name="Cylinder003_BlackMetal001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder003_BlackMetal001_0.geometry}
                  material={materials["BlackMetal.001"]}
                />
              </group>
              <group
                name="Cylinder004"
                position={[-238.081, 9.136, -88.613]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={3.085}
              >
                <mesh
                  name="Cylinder004_BlackMetal002_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder004_BlackMetal002_0.geometry}
                  material={materials["BlackMetal.002"]}
                />
              </group>
              <group
                name="Cube004"
                position={[0, 81.318, 286.387]}
                rotation={[-1.744, 0, 0]}
                scale={[7.67, 1.224, 4.383]}
              >
                <mesh
                  name="Cube004_Steel_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube004_Steel_0.geometry}
                  material={materials.Steel}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/excavator.glb");
