/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MaX3Dd (https://sketchfab.com/MaX3Dd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/claw-hammer-low-poly-350687a05234428ebbed8ba32c3a7ac7
Title: Claw Hammer Low-poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/hammer.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 2.363, 0]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Clawhammer_ClawHammer_0.geometry}
            material={materials.ClawHammer}
            position={[0.027, -0.593, -17.104]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/hammer.glb");
