/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dylan Spin (https://sketchfab.com/DylanSpin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-baboon-50dab8a3d71a4929937c511536414011
Title: Low Poly Baboon
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/monkey.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="0831344893f141608f0550e9d4cbf10cfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode">
              <group
                name="Cube"
                position={[0, 353.265, -145.684]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[148.969, 100, 100]}
              >
                <mesh
                  name="Cube_Lighter_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_Lighter_0.geometry}
                  material={materials.Lighter}
                />
                <mesh
                  name="Cube_Body_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_Body_0.geometry}
                  material={materials.Body}
                />
                <mesh
                  name="Cube_face_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_face_0.geometry}
                  material={materials.face}
                />
                <mesh
                  name="Cube_Eye_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_Eye_0.geometry}
                  material={materials.material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/monkey.glb");
