/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Michael Makivic (https://sketchfab.com/makivic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/weathered-wrench-game-model-66b29c557ce04bb0b14bdde2cc204a2f
Title: Weathered Wrench (Game Model)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Wrench(props) {
  const { nodes, materials } = useGLTF("/models/wrench.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -53.652, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wrench_low__0.geometry}
          material={materials.RootNode}
          position={[0, 2.597, -3.483]}
        />
      </group>
      <group position={[0, -53.652, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object001__0.geometry}
          material={materials.RootNode}
          position={[0, 2.597, -3.483]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/modelswrench.glb");
